MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: MobileNet.MobileNet_v1_conv12_body
  FASTER_RCNN: True
NUM_GPUS: 8
MOBILENET:
  FREEZE_AT: 5
SOLVER:
  WEIGHT_DECAY: 0.00004
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: MobileNet.MobileNet_v1_roi_conv_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/mobilenet_v1.pth'
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
